Companions/Models/edit.cs
using System.ComponentModel.DataAnnotations;

namespace Companions.Models
{
    public class edit
    {
        [Display(Name = "Откуда")]
        public string departure { get; set; }


        [Display(Name = "Куда")]
        public string arrival { get; set; }


        [Display(Name = "Туда")]
        public string Cty1 { get; set; }


        [Display(Name = "Обратно")]
        public string Cty2 { get; set; }


        [Display(Name = "Количество мест")]
        public string cms { get; set; }


        [Display(Name = "Автомобиль")]
        public string auto { get; set; }


        [Display(Name = "Цена одной поездки")]
        public string cost { get; set; }
    }
}

Companions/Controllers/ClientController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Companions.Models;
using Microsoft.EntityFrameworkCore.Query.SqlExpressions;

using System.Security.Claims;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;

using System.Security.Claims;

using Microsoft.Data.SqlClient;
using System;
using System.Data;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Companions.Models.Updates;
using Companions.Models.Database;

namespace Companions.Controllers
{
    public class ClientController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Create()
        {
            return View();
        }
        public ActionResult done()
        {
            return View();
        }

        [HttpPost]
        public ActionResult createSuggestion(string departure, string arrival, string ddate, string edate, string count, bool ifdriver, bool ifpassanger, bool smoking, bool pet, bool dialogue, string cost, string auto)
        {
                int _smoking = smoking ? 1 : 0;
                int _pet = pet ? 1 : 0;
                int _dialogue = dialogue ? 1 : 0;
                int _pass;
                if (ifdriver && !ifpassanger) _pass = 0;
                else _pass = 1;
                string connectionString = "Data Source=(localdb)\\MSSQLLocalDB;Initial Catalog=CompanionDB;TrustServerCertificate=true;Integrated Security=SSPI";
                string sqlExpression = $"INSERT INTO Suggestions" +
                    $" VALUES (N'{User.Identity.Name}', {_pass}, N'{departure}', N'{arrival}', '{ddate}', '{edate}', {count}, 0, '{auto}', {cost}, {_smoking}, {_pet}, {_dialogue});";
                List<Suggestions> l = new List<Suggestions>();

                using (SqlConnection connection = new SqlConnection(connectionString))
                {
                    connection.Open();

                    SqlCommand command = new SqlCommand(sqlExpression, connection);
                    SqlDataReader reader = command.ExecuteReader();
                }
                Response.Redirect("/Client/SuccessfullySugegstion");
                return View();
        }

        public ActionResult SuccessfullySugegstion()
        {
            return View();
        }

        public ActionResult Respond(int id)
        {
            ViewBag.Id = id;
            ViewBag.UserID = User.Identity.Name;

            string sqlExpression = $"SELECT * FROM Suggestions WHERE Id={id}";
            Suggestions item = new Suggestions();
            try
            {
                using (SqlConnection connection = new SqlConnection(Database.connectionString))
                {
                    connection.Open();

                    SqlCommand command = new SqlCommand(sqlExpression, connection);
                    SqlDataReader reader = command.ExecuteReader();

                    if (reader.HasRows) // если есть данные
                    {
                        while (reader.Read())
                        {
                            item.id = Convert.ToInt32(reader.GetValue(0));
                            item.departureCity = reader.GetValue(3).ToString();
                            item.arrivalCity = reader.GetValue(4).ToString();
                            if (reader.GetValue(5) != DBNull.Value) item.ArrivalDestinationDate = reader.GetValue(5).ToString();
                            if (reader.GetValue(6) != DBNull.Value) item.ArrivalDepartureDate = reader.GetValue(6).ToString();
                            if (reader.GetValue(7) != DBNull.Value) item.CountOfCompanions = Convert.ToInt32(reader.GetValue(7));
                            item.UserPublished = reader.GetValue(1).ToString();
                            if (reader.GetValue(10) != DBNull.Value) item.TravelCost = Convert.ToInt32(reader.GetValue(10));
                            if (reader.GetValue(8) != DBNull.Value) item.AlreadySentApplication = Convert.ToInt32(reader.GetValue(8));
                            if (reader.GetValue(9) != DBNull.Value) item.Automobile = reader.GetValue(9).ToString();

                            if (reader.GetValue(11) != DBNull.Value) item.smoking = reader.GetBoolean(11);
                            if (reader.GetValue(12) != DBNull.Value) item.pet = reader.GetBoolean(12);
                            if (reader.GetValue(13) != DBNull.Value) item.dialogue = reader.GetBoolean(13);

                            if (Convert.ToBoolean(reader.GetValue(2)))
                                item.Traveller = "Попутчик";
                            else
                                item.Traveller = "Путешественник";
                        }
                    }

                    reader.Close();
                    ViewBag.l = item;
                    ViewBag.User = item.UserPublished;
                }

                return View();
            }
            catch
            {
                Response.Redirect("/Error/Exception");

                return View();
            }
        }

        public ActionResult Send(int id, int free)
        {
            ViewBag.Id = id;
            ViewBag.UserID = User.Identity.Name;
            ViewBag.Free = free;

            return View();
        }

        [HttpPost]
        public void SendRequest(string id, string count, string option, string money, string message, string free)
        {
            int all = 0, there = 0, back = 0;
            if (option == "all") all = 1;
            else if (option == "there") there = 1;
            else if (option == "back") back = 1;

            if (Convert.ToInt32(count) > Convert.ToInt32(free))
            {
                Response.Redirect($"/Client/errormanyfellow");
            }

            else
            {
                try
                {
                    string sqlExpression = $"INSERT INTO Responses (idSuggestion, UserResponsed, Date, Verdict, Count, OnlyThere, OnlyBack, ThereBack, SuggestedMoney, Message)" +
                        $"VALUES ({id}, '{User.Identity.Name}', NULL, NULL, {count}, {there}, {back}, {all}, {money}, N'{message}');";
                    //return Content(sqlExpression);
                    List<Suggestions> l = new List<Suggestions>();

                    using (SqlConnection connection = new SqlConnection(Database.connectionString))
                    {
                        connection.Open();

                        SqlCommand command = new SqlCommand(sqlExpression, connection);
                        SqlDataReader reader = command.ExecuteReader();
                    }


                    sqlExpression = $"SELECT * FROM Suggestions " +
                        $"WHERE Id={id}";

                    string UID = "";
                    using (SqlConnection connection = new SqlConnection(Database.connectionString))
                    {
                        connection.Open();

                        SqlCommand command = new SqlCommand(sqlExpression, connection);
                        SqlDataReader reader = command.ExecuteReader();

                        if (reader.HasRows) // если есть данные
                        {
                            while (reader.Read())
                            {
                                UID = reader.GetString(1);
                            }
                        }
                    }

                    sqlExpression = $"INSERT INTO Notifications " +
                        $"VALUES ('{UID}', N'На Вашу поездку пришёл новый отклик. Скорее посмотрите, что там!', 0);";

                    using (SqlConnection connection = new SqlConnection(Database.connectionString))
                    {
                        connection.Open();

                        SqlCommand command = new SqlCommand(sqlExpression, connection);
                        SqlDataReader reader = command.ExecuteReader();
                    }


                    Response.Redirect($"/Client/Successfully?user={UID}");
                }
                catch
                {
                    Response.Redirect("/Error/Exception");
                }
            }
        }


        public ActionResult errormanyfellow()
        {
            return View();
        }

        public ActionResult Edit(parametrs pr)
        {
            //ViewBag.User = User.Identity.GetUserId();
            ViewBag.IfTourist = (pr.ift == 1 ? true : false);
            ViewBag.Id = pr.id;
            ViewBag.UserId = pr.uid;

            var user = User.Identity.Name;

            if (user == pr.uid)
            {
                try
                {
                    string sqlExpression = $"SELECT * FROM Suggestions WHERE Id={pr.id}";
                    Suggestions item = new Suggestions();
                    using (SqlConnection connection = new SqlConnection(Database.connectionString))
                    {
                        connection.Open();

                        SqlCommand command = new SqlCommand(sqlExpression, connection);
                        SqlDataReader reader = command.ExecuteReader();

                        if (reader.HasRows) // если есть данные
                        {
                            while (reader.Read())
                            {
                                item.id = Convert.ToInt32(reader.GetValue(0));
                                item.departureCity = reader.GetValue(3).ToString();
                                item.arrivalCity = reader.GetValue(4).ToString();
                                if (reader.GetValue(5) != DBNull.Value) item.ArrivalDestinationDate = reader.GetValue(5).ToString();

Companions/Views/Client/Adress.cshtml
@model Suggestions

@{
}


<h4>Куда едем?</h4>
<form method="post" asp-controller="Client" asp-action="Idea">
    <div class="form-floating">
        <input class="form-control" required aria-required="true" type="text" asp-for="departureCity" id="departure" name="departure" aria-required="true" data-val-required="Это поле обязательно.">
        <label class="form-label" asp-for="departureCity">Откуда</label>
        <span class="text-danger field-validation-valid" data-valmsg-for="departure" data-valmsg-replace="true"></span>
    </div>


    <div class="form-floating">
        <input class="form-control" required aria-required="true" type="text" asp-for="arrivalCity" id="arrival" name="arrival" aria-required="true" data-val-required="Это поле обязательно.">
        <label class="form-label" asp-for="arrivalCity">Куда</label>
        <span class="text-danger field-validation-valid" data-valmsg-for="departure" data-valmsg-replace="true"></span>
    </div>


    <input id="submit" type="submit" value="Далее" class="w-100 btn btn-lg btn-primary">
</form>

Companions/Views/Client/AllResults.cshtml
@{
    string[] TableHeaders = new string[] {
                        ""
                        ,"Кто"
                        ,"Откуда"
                        ,"Куда"
                        ,"Туда"
                        ,"Обратно"
                        ,"Мест"
                        ,"Забронировано"
                        ,"Автомобиль"
                        ,"Предлагаемая цена"
    };
}

<div class="text-center">
    <h4>Вот, что мы нашли:</h4>
    <div class="table">
        <table class="table">
            <thead>
                <tr>
                    @{
                        foreach (var head in TableHeaders)
                        {
                            <th>
                                @head
                            </th>
                        }
                    }
                </tr>
            </thead>

            <tbody>
                @{
                    if (Model != null)
                    {
                        foreach (var Data in Model)
                        {
                            <tr>
                                <td>@Data.UserPublished</td>
                                @if (Data.Traveller == "Путешественник")
                                {
                                    <td>🚙</td>
                                }
                                else
                                {
                                    <td>🙍‍</td>
                                }
                                <td>@Data.departureCity</td>
                                <td>@Data.arrivalCity</td>
                                @if (Data.ArrivalDepartureDate == null && Data.ArrivalDestinationDate != null)
                                {
                                    <td>@Data.ArrivalDestinationDate</td>
                                    <td>В одну сторону</td>
                                }
                                else if (Data.ArrivalDepartureDate != null && Data.ArrivalDestinationDate == null)
                                {
                                    <td>В одну сторону</td>
                                    <td>@Data.ArrivalDepartureDate</td>
                                }
                                else if (Data.ArrivalDepartureDate == null && Data.ArrivalDestinationDate == null)
                                {
                                    <td colspan="2" style="text-align:center;">Без уточнённой даты</td>
                                }
                                else
                                {
                                    <td>@Data.ArrivalDestinationDate</td>
                                    <td>@Data.ArrivalDepartureDate</td>
                                }
                                <td style="text-align:center;">@Data.CountOfCompanions</td>

                                @if (Data.Traveller == "Путешественник")
                                {
                                    <td style="text-align:center;">@Data.AlreadySentApplication</td>
                                }
                                else
                                {
                                    <td style="text-align:center;">-</td>
                                }

                                @if (Data.Automobile == null)
                                {
                                    <td style="text-align:center;">-</td>
                                }
                                else
                                {
                                    <td style="text-align:center;">@Data.Automobile</td>
                                }
                                @if (Data.TravelCost == 0)
                                {
                                    <td>Без цены</td>
                                }
                                else
                                {
                                    <td>@Data.TravelCost ₽</td>
                                }

                                @if (Data.UserPublished != null)
                                {
                                    string str = "/Client/Respond/" + Data.id;
                                    <td><a class='btn btn-primary btn-sm' href=@str>Откликнуться</a></td>
                                }
                            </tr>
                        }
                    }
                }
            </tbody>
        </table>
    </div>
</div>

Companions/Views/Client/Delete.cshtml
@{
    ViewData["Title"] = "Удаление";
}

<div id="r1">
    <br />
    <h1>✅</h1>
    <h3>Поездка удалена</h3>
    <p>Поездка и все отклики на неё были удалены безвозвратно.</p>

    <a class='btn btn-primary btn-sm' href='/List'>Все поездки</a>
    <a class='btn btn-primary btn-sm' href='/Home/Index'>На главную страницу</a>
</div>

Companions/Views/Client/Edit.cshtml
@model edit
@{}

<h2>Редактирование заявки №@ViewBag.Id</h2>

<form method="post" asp-controller="Client" asp-action="submitchanges">

    <input name="id" value=@ViewBag.Id type="hidden"/>


    <div class="form-floating">
        <input class="form-control" required aria-required="true" type="text" asp-for="departure" id="departure" name="departure" value=@ViewBag.l.departureCity aria-required="true" data-val-required="Это поле обязательно.">
        <label class="form-label" asp-for="departure">Откуда</label>
        <span class="text-danger field-validation-valid" data-valmsg-for="departure" data-valmsg-replace="true"></span>
    </div>

    <div class="form-floating">
        <input class="form-control" required aria-required="true" type="text" asp-for="arrival" id="arrival" name="arrival" value=@ViewBag.l.arrivalCity aria-required="true" data-val-required="Это поле обязательно.">
        <label class="form-label" asp-for="arrival">Куда</label>
        <span class="text-danger field-validation-valid" data-valmsg-for="arrival" data-valmsg-replace="true"></span>
    </div>

    <div class="form-floating">
        <input class="form-control" required aria-required="true" type="datetime-local" asp-for="Cty1" id="Cty1" name="Cty1" value=@ViewBag.l.ArrivalDestinationDate>
        <label class="form-label" asp-for="Cty1">Отправление туда</label>
    </div>

    <div class="form-floating">
        <input class="form-control" aria-required="true" type="datetime-local" asp-for="Cty2" id="Cty2" name="Cty2" value=@ViewBag.l.ArrivalDepartureDate>
        <label class="form-label" asp-for="Cty2">Отправление обратно</label>
    </div>

    @if (!ViewBag.IfTourist)
    {
        <div class="form-floating">
            <input class="form-control" required aria-required="true" type="text" asp-for="cms" id="cms" name="cms" value=@ViewBag.l.CountOfCompanions aria-required="true" data-val-required="Это поле обязательно.">
            <label class="form-label" asp-for="cms">Количество мест</label>
            <span class="text-danger field-validation-valid" data-valmsg-for="cms" data-valmsg-replace="true"></span>
        </div>
    }

    @if (!ViewBag.IfTourist)
    {
        <div class="form-floating" >
            <input class="form-control" required aria-required="true" type="text" asp-for="auto" id="auto" name="auto" value=@ViewBag.l.Automobile>
            <label class="form-label" asp-for="auto">Автомобиль</label>
        </div>
    }

    <div class="form-floating">
        <input class="form-control" required aria-required="true" type="text" asp-for="cost" id="cost" name="cost" value=@ViewBag.l.TravelCost>
        <label class="form-label" asp-for="cost">Цена</label>
    </div>
    <br />
    <input id="submit" type="submit" value="Сохранить изменения" class="btn btn-primary btn-sm">
    @{
        string DelStr = "/Client/Delete?id=" + @ViewBag.Id + "&pruser=" + ViewBag.UserId;
    }
    <a class='btn btn-danger btn-sm' href=@DelStr>Удалить (БЕЗВОЗВРАТНО)</a>
</form>

Companions/Views/Client/Idea.cshtml
@{
    string[] TableHeaders = new string[] {
                        ""
                        ,"Кто"
                        ,"Откуда"
                        ,"Куда"
                        ,"Туда"
                        ,"Обратно"
                        ,"Мест"
                        ,"Забронировано"
                        ,"Автомобиль"
                        ,"Предлагаемая цена"
            };
}

<div class="text-center">
    <h4>Смотрите, что нашлось:</h4>
    <div class="table">
        <table class="table">
            <thead>
                <tr>
                    @{
                        foreach (var head in TableHeaders)
                        {
                                        <th>
                                            @head
                                        </th>
                        }
                    }
                </tr>
            </thead>

            <tbody>
                @{
                    if (Model != null)
                    {
                        foreach (var Data in Model)
                        {
                                <tr>
                                            <td>@Data.UserPublished</td>
                                            @if (Data.Traveller == "Путешественник")
                                {
                                                <td>🚙</td>
                                }
                                else
                                {
                                                <td>🙍‍</td>
                                }
                                            <td>@Data.departureCity</td>
                                            <td>@Data.arrivalCity</td>
                                            @if (Data.ArrivalDepartureDate == null && Data.ArrivalDestinationDate != null)
                                {
                                                <td>@Data.ArrivalDestinationDate</td>
                                                <td>В одну сторону</td>
                                }
                                else if (Data.ArrivalDepartureDate != null && Data.ArrivalDestinationDate == null)
                                {
                                                <td>В одну сторону</td>
                                                <td>@Data.ArrivalDepartureDate</td>
                                }
                                else if (Data.ArrivalDepartureDate == null && Data.ArrivalDestinationDate == null)
                                {
                                                <td colspan="2" style="text-align:center;">Без уточнённой даты</td>
                                }
                                else
                                {
                                                <td>@Data.ArrivalDestinationDate</td>
                                                <td>@Data.ArrivalDepartureDate</td>
                                }
                                            <td style="text-align:center;">@Data.CountOfCompanions</td>

                                            @if (Data.Traveller == "Путешественник")
                                {
                                                <td style="text-align:center;">@Data.AlreadySentApplication</td>
                                }
                                else
                                {
                                                <td style="text-align:center;">-</td>
                                }

                                            @if (Data.Automobile == null)
                                {
                                                <td style="text-align:center;">-</td>
                                }
                                else
                                {
                                                <td style="text-align:center;">@Data.Automobile</td>
                                }
                                            @if (Data.TravelCost == 0)
                                {
                                                <td>Без цены</td>
                                }
                                else
                                {
                                                <td>@Data.TravelCost ₽</td>
                                }

                                            @if (Data.UserPublished != null)
                                {
                                    string str = "/Client/Respond/" + Data.id;
                                                <td><a class='btn btn-primary btn-sm' href=@str>Откликнуться</a></td>
                                }
                                </tr>
                        }
                    }
                }
            </tbody>
        </table>
    </div>

    <br />
    <br />

    <form method="post" asp-controller="Client" asp-action="AllResults">
        <textarea rows="1" cols="30" name="arrival" style="visibility:hidden;">@ViewData["Arrival"]</textarea>
        <h5>Ничего нету?</h5>
        <input id="submit" type="submit" value="Искать в остальных городах" class="w-100 btn btn-lg btn-primary">
    </form>
</div>

Companions/Views/Client/Respond.cshtml
@{
    ViewData["Title"] = "Отклик";
    int free = ViewBag.l.CountOfCompanions - ViewBag.l.AlreadySentApplication;
}


<h2>Отклик на заявку №@ViewBag.Id</h2>

<h4>Подаём заявку на предложение:</h4>
<p>Имя: @ViewBag.l.UserPublished</p>
@if (ViewBag.l.ArrivalDepartureDate == null && ViewBag.l.ArrivalDestinationDate != null)
{
    <p>Откуда: @ViewBag.l.arrivalCity - @ViewBag.l.ArrivalDepartureDate </p>
    <p>Куда: @ViewBag.l.departureCity</p>
    <p>Обратно: Свободная дата</p>

}
else if (ViewBag.l.ArrivalDepartureDate != null && ViewBag.l.ArrivalDestinationDate == null)
{
    <p>Откуда: @ViewBag.l.departureCity - @ViewBag.l.ArrivalDepartureDate</p>
    <p>Куда: @ViewBag.l.arrivalCity </p>
    <p>Обратно: Свободная дата</p>
}
else if (ViewBag.l.ArrivalDepartureDate == null && ViewBag.l.ArrivalDestinationDate == null)
{
    <p>Откуда: @ViewBag.l.departureCity - Свободная дата</p>
    <p>Куда: @ViewBag.l.arrivalCity </p>
    <p>Обратно: Свободная дата</p>
}
else
{
    <p>Откуда: @ViewBag.l.departureCity - @ViewBag.l.ArrivalDestinationDate</p>
    <p>Куда: @ViewBag.l.arrivalCity </p>
    <p>Обратно: @ViewBag.l.ArrivalDepartureDate</p>
}
<p>Свободно мест: @free</p>
@if (@ViewBag.l.smoking) { <p>🚬 Курю или не против курения</p> }
else {<p>🚭 Не люблю, когда попутчики курят </p>}

@if (@ViewBag.l.pet) { <p>🐾 Рад питомцам</p> }
else {<p>❌ Животные - не моё </p>}

@if (@ViewBag.l.pet) { <p>💬 Готов общаться во время поездки</p> }
else {<p>🤫 Люблю ехать в тишине </p>}

@{
    if (User.Identity.IsAuthenticated)
    {
        if (free != 0)
        {
            <h2>Можем подать заявку от имени @ViewBag.UserID:</h2>
            string adress1 = $"/Chat/im?user={ViewBag.User}";
            string adress2 = $"/Client/Send?id={ViewBag.Id}&free={free}";
            <a class='btn btn-primary btn-sm' href=@adress1>Написать попутчику</a>
            <a class='btn btn-primary btn-sm' href=@adress2>Отправить отклик</a>
        }

        else
        {
            <h2>Ой...</h2>
            <p>Кажется, свободных мест не осталось :(</p>
        }
    }
    else
    {
        <h2>Перед отправкой отклика нужно войти.</h2>
        <a class='btn btn-primary btn-sm' href='/Identity/Account/Register'>Зарегистрироваться</a>
        <a class='btn btn-primary btn-sm' href='/Identity/Account/Login'>Войти</a>
    }
}

Companions/Views/Client/Send.cshtml
@model Response
@{
    ViewData["Title"] = "Отклик";
}

<h2>Отклик на заявку №@ViewBag.Id</h2>

<form method="post" asp-controller="Client" asp-action="SendRequest">

    <input name="id" value=@ViewBag.Id type="hidden" />
    <input name="free" value=@ViewBag.Free type="hidden" />

    <div class="form-floating">
        <input class="form-control" required aria-required="true" type="number" asp-for="Count" id="count" name="count" aria-required="true" data-val-required="Это поле обязательно.">
        <label class="form-label" asp-for="Count">Количество человек:</label>
        <span class="text-danger field-validation-valid" data-valmsg-for="departure" data-valmsg-replace="true"></span>
    </div>

    <div class="form-floating">
        <select class="form-control" asp-for="option" id="option" name="option">
            <option value="all" class="form-control" asp-for="all" id="all" name="all">Туда и обратно</option>
            <option value="there" class="form-control" asp-for="there" id="there" name="there">Только туда</option>
            <option value="back" asp-for="back" id="back" name="back">Только обратно</option>
        </select>
        <label class="form-label" asp-for="option">Выберите:</label>
        <span class="text-danger field-validation-valid" data-valmsg-for="departure" data-valmsg-replace="true"></span>
    </div>

    <div class="form-floating">
        <input class="form-control" required aria-required="true" type="number" asp-for="sugMoney" id="money" name="money" aria-required="true" data-val-required="Это поле обязательно.">
        <label class="form-label" asp-for="sugMoney">Предлагаемая цена поездки:</label>
        <span class="text-danger field-validation-valid" data-valmsg-for="departure" data-valmsg-replace="true"></span>
    </div>

    <div class="form-floating">
        <input class="form-control" required aria-required="true" type="text" asp-for="Message" id="message" name="message">
        <label class="form-label" asp-for="Message">Дополнительное сообщение:</label>
        <span class="text-danger field-validation-valid" data-valmsg-for="departure" data-valmsg-replace="true"></span>
    </div>

    <br />
    <input id="submit" type="submit" value="Отправить заявку" class="w-100 btn btn-lg btn-primary">

</form>

Companions/Views/Client/SuccessfullySugegstion.cshtml
@{
    ViewData["Title"] = "Успех";
}

<div id="r1">
    <br />
    <h1>✅</h1>
    <h3>Поездка создана</h3>
    <p>Ваша поездка уже опубликована, и скоро на неё будут приходить отклики :)</p>

    @{
        <a class='btn btn-primary btn-sm' href='/List'>Список поездок</a>
        <a class='btn btn-primary btn-sm' href='/Client/Trips'>Мои поездки</a>
        <a class='btn btn-primary btn-sm' href='/Home/Index'>На главную страницу</a>
    }
</div>

Companions/Views/Client/createSuggestion.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

Companions/Views/Client/done.cshtml
@{
    ViewData["Title"] = "Успех";
}

<div id="r1">
    <br />
    <h1>✅</h1>
    <h3>Поездка успешно добавлена</h3>
    <p>Поздравляем с новой поездкой! Скоро Вам начнут приходить отклики, поэтому не забывайте регулярно проверять уведомления :)</p>

    <a class='btn btn-primary btn-sm' href='/Client/trips'>Мои поездки</a>
    <a class='btn btn-primary btn-sm' href='/Home/Index'>На главную страницу</a>
</div>

Companions/Views/Client/errormanyfellow.cshtml
@{
    ViewData["Title"] = "Ошибка";
}

<div id="err">
    <br />
    <h2>⚠</h2>
    <h3>Форма заполнена неверно</h3>
    <p>Вы указали слишком много попутчиков: столько мест не найдётся ☹</p>
</div>

Companions/Views/Client/letsgo.cshtml
@{
    ViewData["Title"] = "Успех";
}

<div id="r1">
    <br />
    <h1>✅</h1>
    <h3>Новая поездка добавлена</h3>
    <p>Скоро попутчики смогут отправлять свои отклики на Вашу поездку. Не забудьте их регулярно проверять :)</p>

    <a class='btn btn-primary btn-sm' href='/Responses'>Мои поездки</a>
    <a class='btn btn-primary btn-sm' href='/Home/Index'>На главную страницу</a>
</div>