Companions/Controllers/SignUpController.cs
using Companions.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Text.Json;

namespace Companions.Controllers
{
    public class SignUpController : Controller
    {
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Check(SUModel regData)
        {

            var options = new JsonSerializerOptions
            {
                WriteIndented = true,
                AllowTrailingCommas = true
            };

            using (FileStream fs = new FileStream("Users.json", FileMode.Append))
            {
                //JsonSerializer.Serialize(fs, ",");
                JsonSerializer.Serialize<SUModel>(fs, regData, options);
            }

            return Content(Convert.ToString(regData));
        }
    }
}

Companions/Views/SignUp/Index.cshtml
@model SUModel
@{
    ViewData["Title"] = "Регистрация";
}

<h1>Регистрация</h1>

<form method="post" asp-controller="SignUp" asp-action="Check">
    <label asp-for="login"></label>
    <input asp-for="login" />
    <span asp-validation-for="login"></span>
    
    <label asp-for="password"></label>
    <input asp-for="password" />
    <span asp-validation-for="password"></span>

    <label asp-for="name"></label>
    <input asp-for="name" />
    <span asp-validation-for="name"></span>

    <label asp-for="city"></label>
    <input asp-for="city" />
    <span asp-validation-for="city"></span>

    <input type="submit" value="Войти" />
</form>