Companions/Controllers/ResponsesController.cs
using Companions.Models;
using Companions.Models.Updates;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

using Microsoft.Data.SqlClient;
using System;
using System.Data;
using System.Threading.Tasks;
using Companions.Models.Updates;
using Companions.Models.Database;


namespace Companions.Controllers
{
    public class ResponsesController : Controller
    {
        public ActionResult Index()
        {
            Updates u = new Updates();
            ViewBag.N = u.CheckNotifications(User.Identity.Name);
            ViewBag.M = u.CheckMessages(User.Identity.Name);

            

            string sqlExpression = $"SELECT * FROM Responses WHERE UserResponsed='{User.Identity.Name}'";

            List<Response> l = new List<Response>();

            try
            {

                using (SqlConnection connection = new SqlConnection(Database.connectionString))
                {
                    connection.Open();

                    SqlCommand command = new SqlCommand(sqlExpression, connection);
                    SqlDataReader reader = command.ExecuteReader();

                    if (reader.HasRows) // если есть данные
                    {
                        while (reader.Read())
                        {
                            Response item = new Response();
                            item.idResponse = reader.GetInt32(0);
                            item.IdSuggestion = reader.GetInt32(1);
                            item.UserSend = reader.GetString(2);
                            if (reader.IsDBNull(4))
                            {
                                item.Viewed = false;
                                item.Verdict = false;
                            }

                            else
                            {
                                item.Viewed = true;
                                item.Verdict = reader.GetBoolean(4);
                            }
                            item.Count = reader.GetInt32(5);
                            item.OnlyThere = reader.GetBoolean(6);
                            item.OnlyBack = reader.GetBoolean(7);
                            item.ThereBack = reader.GetBoolean(8);
                            item.sugMoney = reader.GetInt32(9);
                            item.Message = reader.GetString(10);


                            sqlExpression = $"SELECT * FROM Suggestions WHERE Id={item.IdSuggestion};";

                            using (SqlConnection SecondConnection = new SqlConnection(Database.connectionString))
                            {
                                SecondConnection.Open();

                                SqlCommand scommand = new SqlCommand(sqlExpression, SecondConnection);
                                SqlDataReader sreader = scommand.ExecuteReader();

                                if (sreader.HasRows)
                                {
                                    while (sreader.Read())
                                    {
                                        if (sreader.GetValue(3) != DBNull.Value) item.Departure = sreader.GetString(3);
                                        if (sreader.GetValue(5) != DBNull.Value) item.DepartureDate = sreader.GetDateTime(5).ToString();
                                        if (sreader.GetValue(4) != DBNull.Value) item.Destination = sreader.GetString(4);
                                        if (sreader.GetValue(6) != DBNull.Value) item.DestinationDate = sreader.GetDateTime(6).ToString();
                                    }
                                }

                                sreader.Close();
                            }

                            l.Add(item);

                        }
                    }
                    reader.Close();
                }



                return View(l);
            }


            catch
            {
                Response.Redirect("/Error/Exception");
                return View();
            }
        }

        public ActionResult My()
        {
            Updates u = new Updates();
            ViewBag.N = u.CheckNotifications(User.Identity.Name);
            ViewBag.M = u.CheckMessages(User.Identity.Name);

            try
            {

                
                List<Response> l = new List<Response>();
                string sqlExpression = $"SELECT * FROM Suggestions WHERE UserPublished='{User.Identity.Name}';";
                using (SqlConnection IDConnection = new SqlConnection(Database.connectionString))
                {
                    IDConnection.Open();

                    SqlCommand idcommand = new SqlCommand(sqlExpression, IDConnection);
                    SqlDataReader idreader = idcommand.ExecuteReader();

                    if (idreader.HasRows)
                    {
                        while (idreader.Read())
                        {
                            sqlExpression = $"SELECT * FROM Responses WHERE IdSuggestion={idreader.GetInt32(0)}";

                            using (SqlConnection connection = new SqlConnection(Database.connectionString))
                            {
                                connection.Open();

                                SqlCommand command = new SqlCommand(sqlExpression, connection);
                                SqlDataReader reader = command.ExecuteReader();

                                if (reader.HasRows) // если есть данные
                                {
                                    while (reader.Read())
                                    {
                                        Response item = new Response();
                                        item.idResponse = reader.GetInt32(0);
                                        item.IdSuggestion = reader.GetInt32(1);
                                        item.UserSend = reader.GetString(2);
                                        if (reader.IsDBNull(4))
                                        {
                                            item.Viewed = false;
                                            item.Verdict = false;
                                        }

                                        else
                                        {
                                            item.Viewed = true;
                                            item.Verdict = reader.GetBoolean(4);
                                        }
                                        item.Count = reader.GetInt32(5);
                                        item.OnlyThere = reader.GetBoolean(6);
                                        item.OnlyBack = reader.GetBoolean(7);
                                        item.ThereBack = reader.GetBoolean(8);
                                        item.sugMoney = reader.GetInt32(9);
                                        item.Message = reader.GetString(10);


                                        sqlExpression = $"SELECT * FROM Suggestions WHERE Id={item.IdSuggestion};";

                                        using (SqlConnection SecondConnection = new SqlConnection(Database.connectionString))
                                        {
                                            SecondConnection.Open();

                                            SqlCommand scommand = new SqlCommand(sqlExpression, SecondConnection);
                                            SqlDataReader sreader = scommand.ExecuteReader();

                                            if (sreader.HasRows)
                                            {
                                                while (sreader.Read())
                                                {
                                                    if (sreader.GetValue(3) != DBNull.Value) item.Departure = sreader.GetString(3);
                                                    if (sreader.GetValue(5) != DBNull.Value) item.DepartureDate = sreader.GetDateTime(5).ToString();
                                                    if (sreader.GetValue(4) != DBNull.Value) item.Destination = sreader.GetString(4);
                                                    if (sreader.GetValue(6) != DBNull.Value) item.DestinationDate = sreader.GetDateTime(6).ToString();
                                                }
                                            }

                                            sreader.Close();
                                        }

                                        l.Add(item);

                                    }
                                }
                                reader.Close();
                            }
                        }
                    }

                    idreader.Close();
                }
                return View(l);
            }


            catch
            {
                Response.Redirect("/Error/Exception");
                return View();
            }
        }

        public class arguments
        {
            public int id;
            public bool Verdict;
        }


        [HttpPost]
        public ActionResult Approve(int id) // одобрить заявку
        {
            try
            {

                
                string sqlExpression = $"UPDATE Responses " +
                    $"SET Verdict=1 " +
                    $"WHERE idResponse={id}";

                using (SqlConnection connection = new SqlConnection(Database.connectionString))
                {
                    connection.Open();

                    SqlCommand command = new SqlCommand(sqlExpression, connection);
                    SqlDataReader reader = command.ExecuteReader();
                }



Companions/Views/Responses/Approve.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

Companions/Views/Responses/Deflect.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

Companions/Views/Responses/Index.cshtml
@{
    ViewData["Title"] = "Мои отклики";
    string[] TableHeaders = new string[] {
                        "№"
                        ,"Куда"
                        ,"Откуда"
                        ,"Туда"
                        ,"Обратно"
                        ,"Кол-во мест"
                        ,"Предложено"
                        ,"Сообщение"
                        ,"Ответ"
    };
}


@if (User.Identity.IsAuthenticated)
{
    <br />
    <table>
        <tr>
            @if (ViewBag.N)
            {
                <th style="background-color:beige;border-radius:5px;">
                    <div class="colr" style="margin:10px;">
                        <h5 style="text-align:center;">🔔</h5>
                    </div>
                </th>
            }
            @if (ViewBag.M)
            {
                <th style="background-color:lightskyblue;border-radius:5px;">
                    <div class="mesl" style="margin:10px;">
                        <h5 style="text-align:center;">💬</h5>
                    </div>
                </th>
            }
        </tr>
    </table>

    <br />
    <br/>
}

<h1>Ваши отклики</h1>

@if (User.Identity.IsAuthenticated)
{

    <div class="table">
        <table class="table" id="table">
            <thead>
                <tr>
                    @{
                        foreach (var head in TableHeaders)
                        {
                            <th>
                                @head
                            </th>
                        }
                    }
                </tr>
            </thead>

            <tbody>
                @{
                    if (Model != null)
                    {
                        foreach (var Data in Model)
                        {
                            <tr>
                                <td>@Data.idResponse</td>

                                @{
                                    if (Data.ThereBack)
                                    {
                                        <td>@Data.Departure</td>
                                        <td>@Data.Destination</td>
                                        <td>@Data.DepartureDate</td>
                                        <td>@Data.DestinationDate</td>
                                    }

                                    else if (Data.OnlyThere)
                                    {
                                        <td>@Data.Departure</td>
                                        <td>@Data.Destination</td>
                                        <td>@Data.DepartureDate</td>
                                        <td>Только туда</td>
                                    }

                                    
                                    else if (Data.OnlyBack)
                                    {
                                        <td>@Data.Departure</td>
                                        <td>@Data.Destination</td>
                                        <td>Только обратно</td>
                                        <td>@Data.DestinationDate</td>
                                    }
                                }

                                
                                <td>@Data.Count</td>
                                <td>@Data.sugMoney</td>
                                <td>@Data.Message</td>
                                @{
                                    if (Data.Viewed == false)
                                    {
                                        <td>Пока без ответа</td>
                                    }
                                    else
                                    {
                                        if (Data.Verdict)
                                        {
                                            <td style = "color:green;">Поездка одобрена</td>
                                        }
                                        else
                                        {
                                            <td style = "color:red;">Поездка отклонена</td>
                                        }
                                    }
                                }

                            </tr>
                        }
                    }
                }
            </tbody>
        </table>
    </div>
}

else
{
    <div id="error_login">
        <br />
        <h1>❌</h1>
        <h3>Для просмотра своих откликов нужно войти.</h3>

        <a class='btn btn-primary btn-sm' href='/Identity/Account/Register'>Зарегистрироваться</a>
        <a class='btn btn-primary btn-sm' href='/Identity/Account/Login'>Войти</a>
    </div>
}

Companions/Views/Responses/my.cshtml
@{
    ViewData["Title"] = "Мои отклики";
    string[] TableHeaders = new string[] {
                        "№"
                        ,"Поездка"
                        ,"Кто"
                        ,"Туда"
                        ,"Обратно"
                        ,"Кол-во мест"
                        ,"Предложено"
                        ,"Сообщение"
                        ,"Ответ"
    };
}


@if (User.Identity.IsAuthenticated)
{
    <br />
    <table>
        <tr>
            @if (ViewBag.N)
            {
                <th style="background-color:beige;border-radius:5px;">
                    <div class="colr" style="margin:10px;">
                        <h5 style="text-align:center;">🔔</h5>
                    </div>
                </th>
            }
            @if (ViewBag.M)
            {
                <th style="background-color:lightskyblue;border-radius:5px;">
                    <div class="mesl" style="margin:10px;">
                        <h5 style="text-align:center;">💬</h5>
                    </div>
                </th>
            }
        </tr>
    </table>
    <br />
    <br />
}

<h1>Отклики на поездки</h1>

@if (User.Identity.IsAuthenticated)
{

    <div class="table">
        <table class="table" id="table">
            <thead>
                <tr>
                    @{
                        foreach (var head in TableHeaders)
                        {
                            <th>
                                @head
                            </th>
                        }
                    }
                </tr>
            </thead>

            <tbody>
                @{
                    if (Model != null)
                    {
                        foreach (var Data in Model)
                        {
                            <tr>
                                <td>@Data.idResponse</td>
                                <td>@Data.Departure - @Data.Destination</td>
                                <td>@Data.UserSend</td>

                                @{
                                    if (Data.ThereBack)
                                    {
                                        <td>Да</td>
                                        <td>Да</td>
                                    }

                                    else if (Data.OnlyThere)
                                    {
                                        <td>Да</td>
                                        <td style="color:red;">Нет</td>
                                    }

                                    
                                    else if (Data.OnlyBack)
                                    {
                                        <td style="color:red;">Нет</td>
                                        <td>Да</td>
                                    }
                                }

                                
                                <td>@Data.Count</td>
                                <td>@Data.sugMoney</td>
                                <td>@Data.Message</td>
                                
                                    @{
                                        if (!Data.Viewed)
                                        {
                                            <td>
                                                <form method="post" asp-controller="Responses" asp-action="Deflect">
                                                    <input name="id" value=@Data.idResponse type="hidden"/>
                                                    <input id="submit" type="submit" value="Отклонить" class="btn btn-danger btn-sm">
                                                </form>

                                                <form method="post" asp-controller="Responses" asp-action="Approve">
                                                    <input name="id" value=@Data.idResponse type="hidden"/>
                                                    <input id="submit" type="submit" value="Одобрить" class="btn btn-primary btn-sm">
                                                </form>
                                            </td>
                                        }

                                        else
                                        {
                                            if (Data.Verdict)
                                            {
                                                <td style = "color:green;">Поездка одобрена</td>
                                            }
                                            else
                                            {
                                                <td style = "color:red;">Поездка отклонена</td>
                                            }
                                        }
                                    }
                                

                            </tr>
                        }
                    }
                }
            </tbody>
        </table>
    </div>
}

else
{
    <div id="error_login">
        <br />
        <h1>❌</h1>
        <h3>Для просмотра своих откликов нужно войти.</h3>

        <a class='btn btn-primary btn-sm' href='/Identity/Account/Register'>Зарегистрироваться</a>
        <a class='btn btn-primary btn-sm' href='/Identity/Account/Login'>Войти</a>
    </div>
}